description: ''
enabled: true
entry_point: run.py
name: vpc_build_configurations_param_list
parameters:
  action:
    default: build_configurations_param_list
    immutable: true
    type: string
  cls:
    default: VPCConnection
    immutable: true
    type: string
  module_path:
    default: boto.vpc
    immutable: true
    type: string
  params:
    required: true
    type: string
  target_configurations:
    required: true
    type: string
runner_type: run-python
