---
# Used for post message action
post_message_action:
  webhook_url: "https://hooks.slack.com/services/<replace me>"
  username: "my-bot"
  icon_emoji: ":panda_face:"

# Used for Slack sensor
sensor:
  token: ""
  strip_formatting: false

action_token: ""
admin:
  admin_token: ""
  organization: ""
  set_active: true
  attempts: 1
  auto_join_channels:
    - C0123456
