description: Edit general software settings
enabled: true
entry_point: run.py
name: settings_edit
parameters:
  api_action:
    default: settings_edit
    description: settings_edit
    required: false
    type: string
  api_key:
    description: Your API key
    required: false
    type: string
  api_output:
    default: json
    description: xml, json, or serialize (default is XML)
    required: false
    type: string
  dateformat:
    description: 'Date format. Example: %m/%d/%Y'
    required: true
    type: string
  datetimeformat:
    description: 'Date/Time format. Example: %m/%d/%Y %H:%M'
    required: true
    type: string
  timeformat:
    description: 'Time format. Example: %H:%M'
    required: true
    type: string
runner_type: run-python
