---
token: ""
user: ""
password: ""
BASE_URL: "https://github.com"  # can also be a GitHub Enterprise URL

repository_sensor:
  event_type_whitelist:
    - "IssuesEvent"
    - "IssueCommentEvent"
    - "ForkEvent"
    - "WatchEvent"
    - "ReleaseEvent"
    - "PushEvent"

  repositories:
    -
      user: "StackStorm"
      name: "st2"
    -
      user: "StackStorm"
      name: "st2contrib"
  count: 30  # Maximum number of old events to retrieve
