---
ref: ansible
name : ansible
description : st2 content pack containing ansible integrations
keywords:
  - ansible
  - cfg management
  - configuration management
version : 0.3.0
author : StackStorm, Inc.
email : info@stackstorm.com